### PR TITLE
Added an open-source healthcare project

### PR DESCRIPTION
**Pull request by laignelet16**
To replace HospitalRun which is archived, I added [OpenEMR](https://www.open-emr.org/). This system serves as an Electronic Health Records (EMR) platform and a solution for managing medical practices.

### CODE REVIEW

**Comment by joannakl** [comment]
is this related to any of the open issues?

**Comment by laignelet16** [comment]
Hello, yes it is for issue #104

**Comment by joannakl** [comment]
closes #104

**Comment by joannakl** [comment]
closes #104

**Pull request merged**
